defmodule MoodleNet.AP.CollectionAspect do
  use ActivityPub.Aspect, persistence: MoodleNet.AP.SQLCollectionAspect,
    name: "mn_collection_aspect"

  aspect do
    assoc(:resources, type: "Collection", functional: true, autogenerated: true)
    assoc(:subcollections, type: "Collection", functional: true, autogenerated: true)
    assoc(:threads, type: "Collection", functional: true, autogenerated: true, repeated: true)
  end

  def autogenerate(:resources, _entity),
    do: ActivityPub.new(%{type: "Collection"})

  def autogenerate(:subcollections, _entity),
    do: ActivityPub.new(%{type: "Collection"})

  def autogenerate(:threads, _entity),
    do: ActivityPub.new(%{type: "Collection"})
end
