defmodule MoodleNet.AP.CollectionAspect do
  use ActivityPub.Aspect, persistence: MoodleNet.AP.SQLCollectionAspect,
    name: "mn_collection_aspect"

  require ActivityPub.Guards, as: APG

  aspect do
    assoc(:resources, type: "Collection", functional: true, autogenerated: true)
    assoc(:subcollections, type: "Collection", functional: true, autogenerated: true)
  end

  def autogenerate(:resources, entity),
    do: ActivityPub.new(%{type: "Collection"})

  def autogenerate(:subcollections, entity),
    do: ActivityPub.new(%{type: "Collection"})
end
