FROM elixir:1.10.4-alpine

ENV HOME=/opt/app/ TERM=xterm

WORKDIR $HOME

# dev deps
RUN apk update && \
    apk add --no-cache bash openssl-dev inotify-tools 

# useful deps
RUN apk add --no-cache curl git rust cargo npm build-base

# dependencies for comeonin
RUN apk add --no-cache cmake make gcc libc-dev

EXPOSE 4000/tcp
EXPOSE 4004/tcp

CMD trap 'exit' INT; iex -S mix phx.server
