#!/usr/bin/with-contenv sh

if [ ! -z "$PROXY_FRONTEND_URL" ]; then

 echo "Starting web server proxy..."

 if [ "$WEBSERVER_CHOICE" = "caddy" ]; then

  echo "Using caddy web server..."

  exec caddy --conf /caddy/Caddyfile

 else

  echo "Using nginx web server..."

  export DOLLAR='$'
  # prepare our nginx config based on env vars
  envsubst < /etc/nginx/conf.d/mnet.template > /etc/nginx/conf.d/mnet.conf
  cat /etc/nginx/conf.d/mnet.conf

  exec nginx -g "daemon off;"

 fi

fi
