"""
A resource which is useful to people or the ecosystem.
"""
type EconomicResource {
  id: ID!

  """
  An informal or formal textual identifier for an item. Does not imply uniqueness.
  """
  name: String

  """
  References one or more concepts in a common taxonomy or other classification
  scheme for purposes of categorization or grouping.
  """
  classifiedAs: [URI!]

  """
  The primary resource specification or definition of an existing or potential
  economic resource. A resource will have only one, as this specifies exactly
  what the resource is.
  """
  conformsTo: ResourceSpecification!

  """
  Sometimes called serial number, used when each item must have a traceable
  identifier (like a computer). Could also be used for other unique tracking
  identifiers needed for resources.
  """
  trackingIdentifier: String

  """
  Lot or batch of an economic resource, used to track forward or backwards to
  all occurrences of resources of that lot. Note more than one resource can be
  of the same lot.
  """
  lot: ProductBatch

  """
  The uri to an image relevant to the resource, such as a photo, diagram, etc.
  """
  image: URI

  """
  The current amount and unit of the economic resource for which the agent has
  primary rights and responsibilities, sometimes thought of as ownership. This
  can be either stored or derived from economic events affecting the resource.
  """
  accountingQuantity: Measure

  """
  The current amount and unit of the economic resource which is under direct
  control of the agent.  It may be more or less than the accounting quantity.
  This can be either stored or derived from economic events affecting the resource.
  """
  onhandQuantity: Measure

  """
  A textual description or comment.
  """
  note: String

  """
  The unit used for use or work or cite actions for this resource.
  """
  unitOfEffort: Unit

  """
  References the ProcessSpecification of the last process the desired economic
  resource went through. Stage is used when the last process is important for
  finding proper resources, such as where the publishing process wants only
  documents that have gone through the editing process.
  """
  stage: ProcessSpecification

  """
  The state of the desired economic resource (pass or fail), after coming out of
  a test or review process. Can be derived from the last event if a pass or fail event.
  """
  state: Action

  """
  Used when a stock economic resource contains items also defined as economic resources.
  """
  containedIn: EconomicResource

  """
  The agent currently with primary rights and responsibilites for the economic
  resource. It is the agent that is associated with the accountingQuantity of
  the economic resource.
  """
  primaryAccountable: Agent

  """
  Used when a stock economic resource contains units also defined as economic resources.
  """
  contains: [EconomicResource!]
  trace: [EconomicEvent!]
  track: [EconomicEvent!]

  """
  The current place an economic resource is located. Could be at any level of
  granularity, from a town to an address to a warehouse location. Usually mappable.
  """
  currentLocation: SpatialThing
}

"""
Input `EconomicResource` type used when sending events to setup initial resource recordings
"""
input EconomicResourceCreateParams {
  """
  An informal or formal textual identifier for an item. Does not imply uniqueness.
  """
  name: String

  """
  (`ResourceSpecification`) The primary resource specification or definition of
  an existing or potential economic resource. A resource will have only one, as
  this specifies exactly what the resource is.
  """
  conformsTo: ID

  """
  Sometimes called serial number, used when each item must have a traceable
  identifier (like a computer). Could also be used for other unique tracking
  identifiers needed for resources.
  """
  trackingIdentifier: String

  """
  (`ProductBatch`) Lot or batch of an economic resource, used to track forward
  or backwards to all occurrences of resources of that lot. Note more than one
  resource can be of the same lot.
  """
  lot: ID

  """
  The uri to an image relevant to the resource, such as a photo, diagram, etc.
  """
  image: URI

  """
  (`EconomicResource`) Used when a stock economic resource contains items also defined as economic resources.
  """
  containedIn: ID

  """
  (`SpatialThing`) The current place an economic resource is located.  Could be
  at any level of granularity, from a town to an address to a warehouse
  location.  Usually mappable.
  """
  currentLocation: ID

  """
  A textual description or comment.
  """
  note: String
}
