"""
An activity that changes inputs into outputs.  It could transform or transport economic resource(s).
"""
type Process {
  id: ID!

  """
  An informal or formal textual identifier for a process. Does not imply uniqueness.
  """
  name: String!

  """
  The planned beginning of the process.
  """
  hasBeginning: DateTime

  """
  The planned end of the process.
  """
  hasEnd: DateTime

  """
  The process is complete or not.  This is irrespective of if the original goal
  has been met, and indicates that no more will be done.
  """
  finished: Boolean

  """
  The definition or specification for a process.
  """
  basedOn: ProcessSpecification

  """
  References one or more concepts in a common taxonomy or other classification
  scheme for purposes of categorization or grouping.
  """
  classifiedAs: [URI!]

  """
  A textual description or comment.
  """
  note: String

  """
  Grouping around something to create a boundary or context, used for documenting, accounting, planning.
  """
  inScopeOf: [AccountingScope!]
  inputs(action: ID): [EconomicEvent!]
  outputs(action: ID): [EconomicEvent!]
  unplannedEconomicEvents(action: ID): [EconomicEvent!]
  nextProcesses: [Process!]
  previousProcesses: [Process!]
  workingAgents: [Agent!]
  trace: [EconomicEvent!]
  track: [EconomicEvent!]

  """
  The process can be safely deleted, has no dependent information.
  """
  deletable: Boolean

  """
  The process with its inputs and outputs is part of the plan.
  """
  plannedWithin: Plan
  committedInputs(action: ID): [Commitment!]
  committedOutputs(action: ID): [Commitment!]
  intendedInputs(action: ID): [Process!]
  intendedOutputs(action: ID): [Process!]

  """
  The process with its inputs and outputs is part of the scenario.
  """
  nestedIn: Scenario
}

input ProcessCreateParams {
  """
  An informal or formal textual identifier for a process. Does not imply uniqueness.
  """
  name: String!

  """
  The planned beginning of the process.
  """
  hasBeginning: DateTime

  """
  The planned end of the process.
  """
  hasEnd: DateTime

  """
  The process is complete or not.  This is irrespective of if the original goal
  has been met, and indicates that no more will be done.
  """
  finished: Boolean

  """
  A textual description or comment.
  """
  note: String

  """
  Grouping around something to create a boundary or context, used for documenting, accounting, planning.
  """
  inScopeOf: [ID!]

  """
  (`Plan`) The process with its inputs and outputs is part of the plan.
  """
  plannedWithin: ID

  """
  (`ProcessSpecification`) The definition or specification for a process.
  """
  basedOn: ID

  """
  References one or more concepts in a common taxonomy or other classification
  scheme for purposes of categorization or grouping.
  """
  classifiedAs: [URI!]
}

type ProcessResponse {
  process: Process
}

"""
Specifies the kind of process.
"""
type ProcessSpecification {
  id: ID!

  """
  An informal or formal textual identifier for the process. Does not imply uniqueness.
  """
  name: String!

  """
  A textual description or comment.
  """
  note: String
}
