defmodule ActivityPub.Association do
  @moduledoc """
  Defines the struct with the properties for an ActivityPub association.
  """
  @enforce_keys [:aspect, :name]
  defstruct aspect: nil,
            name: nil,
            functional: false,
            type: :any,
            autogenerated: false,
            repeated: false,
            inv: false
end
