defmodule ActivityPub.SQL.Associations.BelongsTo do
  @moduledoc """
  Defines the struct with the properties for an ActivityPub.SQL association using a foreign key
  """
  @enforce_keys [:sql_aspect, :aspect, :name]
  defstruct sql_aspect: nil,
    aspect: nil,
    name: nil,
    type: nil,
    autogenerated: nil,
    foreign_key: nil
end
