defmodule ActivityPub.SQL.Associations.Collection do
  @enforce_keys [:sql_aspect, :aspect, :name]
  defstruct sql_aspect: nil,
    aspect: nil,
    name: nil,
    # FIXME this type could be much more useful if it is the final item
    type: "Collection",
    autogenerated: true,
    table_name: "activity_pub_collection_items",
    join_keys: [:subject_id, :target_id],
    repeated: false,
    foreign_key: nil
end
