# MoodleNet: Connecting and empowering educators worldwide
# Copyright © 2018-2019 Moodle Pty Ltd <https://moodle.com/moodlenet/>
# Contains code from Pleroma <https://pleroma.social/> and CommonsPub <https://commonspub.org/>
# SPDX-License-Identifier: AGPL-3.0-only

defmodule ActivityPub.SQL.Associations.Collection do
  @moduledoc """
  Defines the struct with the properties for an ActivityPub.SQL association using an intermediate collection.
  """
  @enforce_keys [:sql_aspect, :aspect, :name]
  defstruct sql_aspect: nil,
    aspect: nil,
    name: nil,
    # FIXME this type could be much more useful if it is the final item
    type: "Collection",
    autogenerated: true,
    table_name: "activity_pub_collection_items",
    join_keys: [:subject_id, :target_id],
    repeated: false,
    foreign_key: nil
end
