defmodule ActivityPub.SQL.Associations.ManyToMany do
  @enforce_keys [:sql_aspect, :aspect, :name]
  defstruct sql_aspect: nil,
    aspect: nil,
    name: nil,
    type: :any,
    autogenerated: nil,
    table_name: nil,
    join_keys: nil
end
