defmodule ActivityPub.CollectionAspect do
  use ActivityPub.Aspect, persistence: ActivityPub.SQLCollectionAspect

  aspect do
    # FIXME autogenerated is not implemented for fields!
    field(:total_items, :integer, autogenerated: true)
    # FIXME make them virtual?
    # assoc(:current, functional: true)
    # assoc(:first, functional: true)
    # assoc(:last, functional: true)
    # assoc(:items)
    field(:items, :any, virtual: true)

    # FIXME private attribute for the field?
    field(:__ordered__, :boolean)
    # FIXME This should be in SQLCollectionAspect only
    # field(:__table__, :string)
    # field(:__keys__, :string)
  end

  def autogenerate(:total_items, _), do: {:ok, 0}
end
